<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\ChanSortProject.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChanSort.Api\ChanSort.Api.csproj" />
  </ItemGroup>

</Project>
