<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\ChanSortProject.props" />
  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Data.Desktop" Version="25.1.5" />
    <PackageReference Include="DevExpress.Printing.Core" Version="25.1.5" />
    <PackageReference Include="DevExpress.Utils" Version="25.1.5" />
    <PackageReference Include="DevExpress.Win" Version="25.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChanSort.Api\ChanSort.Api.csproj" />
    <ProjectReference Include="..\ChanSort.Loader.LG\ChanSort.Loader.LG.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DevExpress.Data.Desktop.v25.1">
      
    </Reference>
    <Reference Include="DevExpress.Data.v25.1">
      
    </Reference>
    <Reference Include="DevExpress.Drawing.v25.1">
      
    </Reference>
    <Reference Include="DevExpress.Printing.v25.1.Core">
      
    </Reference>
    <Reference Include="DevExpress.Utils.v25.1">
      
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v25.1">
      
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="System.Memory" Version="4.6.3" />
    <PackageReference Update="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>
</Project>