<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <Import Project="..\ChanSortProject.props" />
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChanSort.Api\ChanSort.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="System.Memory" Version="4.6.3" />
    <PackageReference Update="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>

</Project>
