<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\ChanSortProject.props" />
  <ItemGroup>
    <ProjectReference Include="..\ChanSort.Api\ChanSort.Api.csproj" />
    <ProjectReference Include="..\ChanSort.Loader.Panasonic\ChanSort.Loader.Panasonic.csproj" />
    <ProjectReference Include="..\Test.Loader\Test.Loader.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Test.Loader\InitSqlite.cs" Link="InitSqlite.cs" />
  </ItemGroup>
  <Import Project="..\packages\NETStandard.Library.2.0.3\build\net48\NETStandard.Library.targets" Condition="Exists('..\packages\NETStandard.Library.2.0.3\build\net48\NETStandard.Library.targets')" />
  <PropertyGroup>
    <PostBuildEvent>
      $(MSBuildProjectDirectory)\..\deployLibs.cmd $(TargetDir)
</PostBuildEvent>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>